auctions/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.active_listings, name="active_listings"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("add_listing", views.add_listing, name="add_listing"),
    path("listing/<str:id>", views.listing_page, name="listing_page"),
    path("listing/watchlist_management/<str:id>", views.watchlist_management, name="watchlist_management"),
    path("listing/<str:id>/inactive", views.make_listing_inactive, name="inactive"),
    path("<str:username>/watchlist", views.watchlist, name="watchlist"),
    path("<str:username>/myoffers", views.my_offers, name="my_offers"),
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils import timezone
from .auctions_const import *


class User(AbstractUser):
    watchlist = models.ManyToManyField('Listing', blank=True, related_name='watchlist')

class Listing(models.Model):
    title = models.CharField(max_length=LONG_TEXT, null=False)
    description = models.TextField()
    category = models.CharField(max_length=SHORT_TEXT, choices=CATEGORIES, null=True)
    seller = models.ForeignKey(User, on_delete = models.CASCADE, related_name = 'listings')
    winner = models.ForeignKey(User, on_delete = models.CASCADE, related_name = 'winned_bets', null=True, blank=True)
    current_bid = models.DecimalField(max_digits=MAX_DIGITS, decimal_places=DECIMAL_PLACES)
    starting_price = models.DecimalField(max_digits=MAX_DIGITS, decimal_places=DECIMAL_PLACES)
    time_added = models.DateTimeField(auto_now_add=True)
    end_time = models.DateTimeField()
    photo_url = models.URLField(blank=True, null=True)
    active = models.BooleanField(auto_created=True)
    
    def __str__(self):
        return self.title

class Coments(models.Model):
    rating = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(5)])
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name = 'listing_comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comments')
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username} | {self.timestamp}'
    

class Bids(models.Model):
    bid_amount = models.DecimalField(max_digits=MAX_DIGITS, decimal_places=DECIMAL_PLACES, default=10)
    bidder = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_bids')
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name='listing_bids')
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Bid placed by {self.bidder.username}, on {self.listing.title}'
    

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .auction_forms import *
from .utils import is_valid_image_url
from .auctions_const import *
from django.utils import timezone

from .models import *


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("active_listings"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("active_listings"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")


# last finished
def add_listing(request):
    if request.method == 'POST':
        title = request.POST['title']
        description = request.POST['description']
        category = request.POST['category']
        end_time = request.POST['end_time']
        starting_price = request.POST['starting_price']
        photo_url = request.POST['photo_url']

        if not title or not description or len(title) > LONG_TEXT or not is_valid_image_url(photo_url):
            return render(request, 'auctions/add_listing.html', {
                'categories': CATEGORIES,
                'title': title,
                'description': description,
                'category': category,
                'end_time': end_time,
                'starting_price': starting_price,
                'photo_url': photo_url,
                'error_msg': 'Please provide correct input'
            })
        else: 
            seller_id = request.user
            listing = Listing(title=title, description=description, category=category, end_time=end_time, starting_price=starting_price, photo_url=photo_url, current_bid=starting_price, seller=seller_id, active=True)
            listing.save()
            
    return render(request, 'auctions/add_listing.html', {
        'categories': CATEGORIES,
    })
    
def active_listings(request):
    active = Listing.objects.filter(end_time__gt=timezone.now(), active=True).order_by('-time_added')
    return render(request, 'auctions/active_listings.html', {
        'active_listings': active,
    })

def listing_page(request, id):
    current = Listing.objects.get(id=id)
    if request.user.is_authenticated:
        is_assigned = request.user.watchlist.filter(id=current.id).exists()
    else:
        is_assigned = False

    return render(request, 'auctions/listing_page.html', {
        'listing': current,
        'is_assigned': is_assigned,
    })

def watchlist_management(request, id):
    if request.method == 'POST':
        if request.user.is_authenticated:
            if request.user.watchlist.filter(id=id).exists():
                listing = Listing.objects.get(id=id)
                request.user.watchlist.remove(listing)
            else:
                user = request.user
                listing = Listing.objects.get(id=id)
                user.watchlist.add(listing)

        return HttpResponseRedirect(reverse("listing_page", args=(id,)))

def make_listing_inactive(request, id):
    listing = Listing.objects.get(id=id)
    listing.active = False
    listing.save()

    if listing.current_bid.bidder != lisgint.seller:
        listing.winner = listing.current_bid.bidder

    return HttpResponseRedirect(reverse("listing_page", args=(id,)))

def watchlist(request, username):
    my_list = request.user.watchlist.all()
    return render(request, 'auctions/listing_offers.html', {
        'my_list': my_list,
    })

def my_offers(request, username):
    my_list = request.user.listings.all()
    return render(request, 'auctions/listing_offers.html', {
        'my_list': my_list,
    })

auctions/templates/auctions/active_listings.html
{% extends 'auctions/layout.html' %}

{% block body %}

{% for listing in active_listings %}
<a href="{% url 'listing_page' listing.id %}">
<div class="listing">
    <p class="listing_title">Title: {{ listing.title }}</p>
    <p class="listing_description">Description: {{ listing.description }}</p>
    <p class="current_price">Current bid: {{ listing.current_bid }}</p>
    <p class="time_added">Added: {{ listing.time_added }}, by: {{ listing.seller.username }}</p>
    <p><img src="{{ listing.photo_url }}" alt="A picture of an object" width="400"></p>
    <hr>
</div>
</a>
{% endfor %}

{% endblock body %}

auctions/templates/auctions/add_listing.html
{% extends 'auctions/layout.html' %}

{% block body %}

<form action="add_listing" method="post">
    {% csrf_token %}
    
    <div class="form-group">
      <label for="id_title">Auction title:</label>
      <input type="text" name="title" maxlength="255" id="id_title" value="{{ title }}">
    </div>
    
    <div class="form-group">
      <p><label for="id_description">Provide description for your auction:</label></p>
      <textarea name="description" rows="4" id="id_description">{{ description }}</textarea>
    </div>
    
    <div class="form-group">
      <label for="id_category">Category:</label>
      <select name="category" id="id_category" value="{{ category }}">
        {% for category in categories %}
          <option value="{{ category.0 }}">{{ category.1 }}</option>
        {% endfor %}
      </select>
    </div>
    
    <div class="form-group">
      <label for="id_end_time">End time:</label>
      <input type="datetime-local" name="end_time" required id="id_end_time" value="{{ end_time }}">
    </div>
    
    <div class="form-group">
      <label for="id_starting_price">Starting price:</label>
      <input type="number" name="starting_price" step="0.01" min="0" max="99999999.99" required id="id_starting_price">
    </div>

    <div class="form-group">
      <label for="id_photo_url">Photo URL:</label>
      <input type="text" name="photo_url" id="id_photo_url" value="{{ photo_url }}">
    </div>
    <p>{{ error_msg }}</p>
    <button type="submit">Submit</button>
  </form>
  

{% endblock body %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Active Listings</h2>

    TODO
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'active_listings' %}">Active Listings</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a href="{% url 'add_listing' %}" class="nav-link">Add Listing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'watchlist' user.username %}" class="nav-link">Watchlist</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'my_offers' user.username %}" class="nav-link">My offers</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

auctions/templates/auctions/listing_offers.html
{% extends 'auctions/layout.html' %}

{% block body %}

{% for listing in my_list %}
<a href="{% url 'listing_page' listing.id %}">
<div class="listing">
    <p class="listing_title">Title: {{ listing.title }}</p>
    <p class="listint_state">State: {{ listing.active }}</p>
    <p class="listing_description">Description: {{ listing.description }}</p>
    <p class="current_price">Current bid: {{ listing.current_bid }}</p>
    <p class="time_added">Added: {{ listing.time_added }}, by: {{ listing.seller.username }}</p>
    <p><img src="{{ listing.photo_url }}" alt="A picture of an object" width="400"></p>
    <hr>
</div>
</a>
{% endfor %}

{% endblock body %}

auctions/templates/auctions/listing_page.html
{% extends 'auctions/layout.html' %}

{% block body %}

<p>Added by {{ listing.seller }} | {{ listing.time_added }}</p>

{% comment %} An ability to close an auction {% endcomment %}
{% if listing.seller == user and listing.active %}
    <form action="{% url 'inactive' listing.id %}" method="post">
    {% csrf_token %}
    <input class="btn btn-primary mb-3" type="submit" value="Close auction">
    </form>
{% elif not listing.active %}
    <p style="color: red">inactive</p>
    {% if listing.winner %}
        <p>Winner: {{ listing.winner.username }}</p>
    {% endif %}
{% endif %}
<h1 class="title">{{ listing.title }}</h1>
<h3 class="description">Description: </h3>
<p>{{ listing.description }}</p>
<p><img src="{{ listing.photo_url }}" alt="Photo of an object" width="600"></p>
<p>Starting price: {{ listing.starting_price }} | Current bid: {{ listing.current_bid }}</p>

{% comment %} Placing bid is user is authenticated {% endcomment %}
{% if user.is_authenticated and listing.active %}
<form action="{% url 'listing_page' listing.id %}" method="post">
    {% csrf_token %}
    <label for="bid">Place your bid: </label>
    <input type="number" name="new_bid" step="0.01" min="0" max="99999999.99" id="id_bid">
    <input type="submit" value="Place">
</form>

{% comment %} Adding to watchlist {% endcomment %}
{% if not is_assigned %}
    <form action="{% url 'watchlist_management' listing.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Add to watchlist">
    </form>
{% else %}
    <form action="{% url 'watchlist_management' listing.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Remove from watchlist">
    </form>
{% endif %}

{% else %}
{% endif %}

{% endblock body %}

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}